resources:
- name: repo
  type: git
  source:
    uri: https://github.com/wsierakowski/learning-cci.git

jobs:
- name: hello-world-job
  plan:
  # Add a get step referencing the resource
  - get: repo
    # tell Concourse to trigger this job when new versions are emitted
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]